// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCM1_qYpPX5gRLs_FvMgRkjSB-SGHDIYU',
    appId: '1:373385381410:web:402cb8be4212cdef306c7b',
    messagingSenderId: '373385381410',
    projectId: 'beast-lifting-app',
    authDomain: 'beast-lifting-app.firebaseapp.com',
    storageBucket: 'beast-lifting-app.firebasestorage.app',
    measurementId: 'G-6D1L28TH28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj2_O-JUH6346FMziKOzJu-ChfJueRDwA',
    appId: '1:373385381410:android:012550aaf3710ec9306c7b',
    messagingSenderId: '373385381410',
    projectId: 'beast-lifting-app',
    storageBucket: 'beast-lifting-app.firebasestorage.app',
  );
}
